<?php
/**
 * @package Blade
 * @subpackage Profile
 * @file
 * Install, update and uninstall functions for the standard installation profile.
 */

use Drupal\blade\Configuration as Blade;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function blade_install()
{
    $conf = new Blade\BladeConfiguration();
    $conf->install();
}
