<?php

define('BLADENEWS_PERMISSION', 'administer rs configuration');
define('BLADENEWS_APP_PERMISSION', 'administer rs application');

function bladenews_boot()
{
    include_once DRUPAL_ROOT.'/sites/all/libraries/autoload.php';
}

/**
 * Implements hook_permission().
 */
function bladenews_permission()
{
    return array(
        BLADENEWS_PERMISSION => array(
          'title' => t('Administer bladenews dataprovider'),
          'description' => t('Access BladeNews configuration page.'),
        ),
        BLADENEWS_FB_APP_PERMISSION => array(
          'title' => t('Administer Facebook dataprovider'),
          'description' => t('Administer Facebook Application ID and SECRET.'),
        ),
  );
}

/**
 *
 * @return array of menu items
 */
function bladenews_menu()
{
    $items = array();

    $items['admin/config/services/fb-provider'] = array(
        'title' => 'Facebook Data Provider',
        'description' => 'Facebook Data Provider',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bladenews_fb_provider_form'),
        'access arguments' => array(BLADENEWS_APP_PERMISSION),
        'file' => 'includes/admin.fb.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/config/services/fb-app'] = array(
        'title' => 'Facebook Application configuration',
        'description' => 'Define Facebook application ID and Secret',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bladenews_fb_app_form'),
        'access arguments' => array(BLADENEWS_PERMISSION),
        'file' => 'includes/admin.fb.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/config/services/twitter-provider'] = array(
        'title' => 'Twitter Provider',
        'description' => 'Twitter Application configuration',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bladenews_twitter_provider_form'),
        'access arguments' => array(BLADENEWS_APP_PERMISSION),
        'file' => 'includes/admin.twitter.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/config/services/twitter-app'] = array(
        'title' => 'Twitter Application configuration',
        'description' => 'Define Twitter application ID and Secret',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bladenews_twitter_app_form'),
        'access arguments' => array(BLADENEWS_PERMISSION),
        'file' => 'includes/admin.twitter.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}
