<?php
/**
 * @package Blade
 * @subpackage DrupalModule
 */

/**
 * implementes drupal HOOK_menu
 * add path products for product landing page
 */
function products_menu()
{
    $items = array();

    $items['products'] = array(
        'title' => 'Products',
        'description' => 'Latests product page',
        'page callback' => 'products_latest',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

/**
 * latests product pages route callback
 */
function products_latest()
{
    return 'test';
}

/**
 * blocks
 *   - 3 latests products in home
 *   - 3 latests available products
 */
function products_block_list()
{
}

function products_block_view()
{
}
